# This is a basic workflow to help you get started with Actions

name: Push dist folder to gh-pages repo

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install sass compiler
        run: |
          mkdir $HOME/.npm-global
          npm config set prefix $HOME/.npm-global
          npm install -g sass

      - name: Clone the dist folder from the gh-pages branch and compile the page.
        run: |
          $GITHUB_WORKSPACE/scripts/create_dist.sh
        env:
          GIT_PASSWORD: ${{ secrets.WORKER_PAT }}
          SASS_PATH: ${{ env.HOME }}/.npm-global/bin/sass

      - name: Pushes the dist folder to the gh-pages branch.
        run: $GITHUB_WORKSPACE/scripts/push_dist_ghp.sh
        env:
          GIT_PASSWORD: ${{ secrets.WORKER_PAT }}
